# **Project : Stock Prediction**

**Import Required Libraries**

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/GOOG.csv')
df

Date        Open        High         Low       Close   Adj Close  \
0    2022-08-08  119.120003  120.860001  117.830002  118.139999  118.139999   
1    2022-08-09  117.989998  118.199997  116.559998  117.500000  117.500000   
2    2022-08-10  119.589996  121.779999  119.360001  120.650002  120.650002   
3    2022-08-11  122.080002  122.339996  119.550003  119.820000  119.820000   
4    2022-08-12  121.160004  122.650002  120.400002  122.650002  122.650002   
..          ...         ...         ...         ...         ...         ...   
245  2023-07-31  133.009995  133.830002  132.130005  133.110001  133.110001   
246  2023-08-01  130.854996  132.919998  130.750000  131.889999  131.889999   
247  2023-08-02  129.839996  130.419998  127.849998  128.639999  128.639999   
248  2023-08-03  128.369995  129.770004  127.775002  128.770004  128.770004   
249  2023-08-04  129.600006  131.929993  128.315002  128.539993  128.539993   

       Volume  
0    17061100  
1    15424300  
2    20497000  
3    16671600  
4    16121100  
..        ...  
245  18381900  
246  22154300  
247  22705800  
248  15018100  
249  20509500  

[250 rows x 7 columns]

In [ ]:
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  2022-08-08  119.120003  120.860001  117.830002  118.139999  118.139999   
1  2022-08-09  117.989998  118.199997  116.559998  117.500000  117.500000   
2  2022-08-10  119.589996  121.779999  119.360001  120.650002  120.650002   
3  2022-08-11  122.080002  122.339996  119.550003  119.820000  119.820000   
4  2022-08-12  121.160004  122.650002  120.400002  122.650002  122.650002   

     Volume  
0  17061100  
1  15424300  
2  20497000  
3  16671600  
4  16121100

In [ ]:
df.tail()

Date        Open        High         Low       Close   Adj Close  \
245  2023-07-31  133.009995  133.830002  132.130005  133.110001  133.110001   
246  2023-08-01  130.854996  132.919998  130.750000  131.889999  131.889999   
247  2023-08-02  129.839996  130.419998  127.849998  128.639999  128.639999   
248  2023-08-03  128.369995  129.770004  127.775002  128.770004  128.770004   
249  2023-08-04  129.600006  131.929993  128.315002  128.539993  128.539993   

       Volume  
245  18381900  
246  22154300  
247  22705800  
248  15018100  
249  20509500

In [ ]:
df.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       250 non-null    object 
 1   Open       250 non-null    float64
 2   High       250 non-null    float64
 3   Low        250 non-null    float64
 4   Close      250 non-null    float64
 5   Adj Close  250 non-null    float64
 6   Volume     250 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 13.8+ KB


**Checking missing values**

In [ ]:
df.isna().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [ ]:
df.describe(include='all')

Date        Open        High         Low       Close  \
count          250  250.000000  250.000000  250.000000  250.000000   
unique         250         NaN         NaN         NaN         NaN   
top     2023-08-04         NaN         NaN         NaN         NaN   
freq             1         NaN         NaN         NaN         NaN   
mean           NaN  105.696616  107.172900  104.519432  105.829780   
std            NaN   12.367202   12.436379   12.389783   12.388743   
min            NaN   85.510002   86.550003   83.449997   83.489998   
25%            NaN   95.749998   97.344997   94.440003   95.835001   
50%            NaN  102.799999  104.205002  101.857502  103.549999   
75%            NaN  117.929998  119.688748  116.782501  118.070002   
max            NaN  133.009995  134.070007  132.130005  133.110001   

         Adj Close        Volume  
count   250.000000  2.500000e+02  
unique         NaN           NaN  
top            NaN           NaN  
freq           NaN           NaN  
mean    105.829780  2.707343e+07  
std      12.388743  1.111356e+07  
min      83.489998  8.567800e+06  
25%      95.835001  2.063240e+07  
50%     103.549999  2.423745e+07  
75%     118.070002  3.022488e+07  
max     133.110001  9.779860e+07

In [ ]:
df['Date']=pd.to_datetime(df['Date'])
df.set_index(df['Date'],inplace=True)

**Remove unwanted columns**

In [ ]:
df.drop(columns=['Open','High','Low','Adj Close','Volume'],inplace=True)

In [ ]:
df.head()

Date       Close
Date                             
2022-08-08 2022-08-08  118.139999
2022-08-09 2022-08-09  117.500000
2022-08-10 2022-08-10  120.650002
2022-08-11 2022-08-11  119.820000
2022-08-12 2022-08-12  122.650002

**Google Stock**

In [ ]:
import plotly.graph_objects as go    
trace1=go.Scatter(
    x=df['Date'],
    y=df['Close'],
    mode='lines',
    name='Data'
)
layout=go.Layout(
    title="Google Stock",
    xaxis={'title':'Date'},
    yaxis={'title':'Close'}
)
fig=go.Figure(
    data=[trace1],
    layout=layout
)
fig.show()

In [ ]:
close_data=df['Close'].values

In [ ]:
close_data

array([118.139999, 117.5     , 120.650002, 119.82    , 122.650002,
       122.879997, 122.510002, 120.32    , 120.860001, 118.120003,
       115.07    , 114.769997, 114.699997, 117.699997, 111.300003,
       110.339996, 109.910004, 109.150002, 110.550003, 108.68    ,
       107.480003, 110.480003, 109.419998, 111.779999, 111.870003,
       105.309998, 105.870003, 103.900002, 103.629997, 103.849998,
       101.830002, 100.010002, 100.57    ,  99.169998,  98.809998,
        98.089996, 100.739998,  98.089996,  96.150002,  99.300003,
       102.410004, 102.220001, 102.239998,  99.57    ,  98.709999,
        98.050003,  98.300003,  99.709999,  97.18    , 100.779999,
       101.389999, 100.290001, 100.529999, 101.480003, 102.970001,
       104.93    ,  94.82    ,  92.599998,  96.580002,  94.660004,
        90.5     ,  87.07    ,  83.489998,  86.699997,  88.650002,
        88.910004,  87.400002,  94.169998,  96.730003,  96.029999,
        98.720001,  98.989998,  98.5     ,  97.800003,  95.830

In [ ]:
#reshape into 2-D array with one column
close_data=close_data.reshape(-1,1)
close_data

array([[118.139999],
       [117.5     ],
       [120.650002],
       [119.82    ],
       [122.650002],
       [122.879997],
       [122.510002],
       [120.32    ],
       [120.860001],
       [118.120003],
       [115.07    ],
       [114.769997],
       [114.699997],
       [117.699997],
       [111.300003],
       [110.339996],
       [109.910004],
       [109.150002],
       [110.550003],
       [108.68    ],
       [107.480003],
       [110.480003],
       [109.419998],
       [111.779999],
       [111.870003],
       [105.309998],
       [105.870003],
       [103.900002],
       [103.629997],
       [103.849998],
       [101.830002],
       [100.010002],
       [100.57    ],
       [ 99.169998],
       [ 98.809998],
       [ 98.089996],
       [100.739998],
       [ 98.089996],
       [ 96.150002],
       [ 99.300003],
       [102.410004],
       [102.220001],
       [102.239998],
       [ 99.57    ],
       [ 98.709999],
       [ 98.050003],
       [ 98.300003],
       [ 99.7

In [ ]:
total_records=len(close_data)

In [ ]:
#80% of data for training
split_perecentage=0.80
split=int(split_perecentage*total_records)
split

200

**Split the data into Training & Testing data**

In [ ]:
close_train=close_data[:split]
close_test=close_data[split:]

In [ ]:
date_train=df['Date'][:split]
date_test=df['Date'][split:]

In [ ]:
import tensorflow as tf
from keras.models import Sequential     
from keras.layers import LSTM,Dense     
from keras.preprocessing.sequence import TimeseriesGenerator

In [ ]:
look_back=15                        
train_generator=TimeseriesGenerator(close_train,close_train,length=look_back,batch_size=20)
test_generator=TimeseriesGenerator(close_test,close_test,length=look_back,batch_size=20)

In [ ]:
#define model
model=Sequential()

model.add(LSTM(10,activation='relu',input_shape=(look_back,1)))
model.add(Dense(1))

**Compile**

In [ ]:
model.compile(optimizer='adam',loss='mse')

In [ ]:
model.fit_generator(train_generator,epochs=1000)

Epoch 1/1000
 7/10 [====================>.........] - ETA: 0s - loss: 3943.9150

<ipython-input-33-be6f90f28a06>:1: UserWarning:

`Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.



10/10 [==============================] - 0s 18ms/step - loss: 3548.9531
Epoch 2/1000
10/10 [==============================] - 0s 18ms/step - loss: 3116.4016
Epoch 3/1000
10/10 [==============================] - 0s 18ms/step - loss: 2554.1978
Epoch 4/1000
10/10 [==============================] - 0s 17ms/step - loss: 968.6497
Epoch 5/1000
10/10 [==============================] - 0s 19ms/step - loss: 680.9602
Epoch 6/1000
10/10 [==============================] - 0s 18ms/step - loss: 423.0995
Epoch 7/1000
10/10 [==============================] - 0s 18ms/step - loss: 311.9388
Epoch 8/1000
10/10 [==============================] - 0s 19ms/step - loss: 345.7666
Epoch 9/1000
10/10 [==============================] - 0s 20ms/step - loss: 351.9143
Epoch 10/1000
10/10 [==============================] - 0s 18ms/step - loss: 330.4429
Epoch 11/1000
10/10 [==============================] - 0s 19ms/step - loss: 352.4808
Epoch 12/1000
10/10 [==============================] - 0s 18ms/step - loss: 314.8892

In [ ]:
prediction=model.predict_generator(test_generator)

<ipython-input-34-4eafd1643ada>:1: UserWarning:

`Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.



In [ ]:
model.save('google_stock_predictor.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning:

You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.



In [ ]:
prediction

array([[116.22369 ],
       [124.54144 ],
       [110.69947 ],
       [123.50763 ],
       [111.277855],
       [123.82708 ],
       [117.903625],
       [106.282845],
       [113.115036],
       [120.070946],
       [122.3454  ],
       [123.33102 ],
       [112.96076 ],
       [125.80366 ],
       [109.25858 ],
       [120.56331 ],
       [110.253204],
       [112.63285 ],
       [119.41672 ],
       [129.44653 ],
       [121.697845],
       [128.34279 ],
       [112.80332 ],
       [126.81964 ],
       [ 99.51719 ],
       [122.17634 ],
       [124.40352 ],
       [118.831985],
       [134.55847 ],
       [122.39879 ],
       [136.6259  ],
       [128.92517 ],
       [135.2617  ],
       [101.71405 ],
       [124.99825 ]], dtype=float32)

In [ ]:
#reshaping back to 1-D
close_train=close_train.reshape((-1))
close_test=close_test.reshape((-1))
prediction=prediction.reshape((-1))

In [ ]:
prediction

array([116.22369 , 124.54144 , 110.69947 , 123.50763 , 111.277855,
       123.82708 , 117.903625, 106.282845, 113.115036, 120.070946,
       122.3454  , 123.33102 , 112.96076 , 125.80366 , 109.25858 ,
       120.56331 , 110.253204, 112.63285 , 119.41672 , 129.44653 ,
       121.697845, 128.34279 , 112.80332 , 126.81964 ,  99.51719 ,
       122.17634 , 124.40352 , 118.831985, 134.55847 , 122.39879 ,
       136.6259  , 128.92517 , 135.2617  , 101.71405 , 124.99825 ],
      dtype=float32)

**Google Stock Prediction**

In [ ]:
#training
trace1=go.Scatter(
    x=date_train,
    y=close_train,
    mode='lines',
    name='Train'
)
#testing
trace2=go.Scatter(
    x=date_test,
    y=close_test,
    mode='lines',
    name='Test'
)
#prediction
trace3=go.Scatter(
    x=date_test,
    y=prediction,
    mode='lines',
    name='Prediction'
)
layout=go.Layout(
    title="Google Stock Prediction",
    xaxis={'title':'Date'},
    yaxis={'title':'Close'}
)
fig=go.Figure(
    data=[trace1,trace2,trace3],
    layout=layout
)
fig.show()
